### ISSUE TITLE
Replace AppVeyor with GitHub Actions

### ISSUE THREAD

**Issue by eXpl0it3r** [eXpl0it3r/Schiffbruch#13]
With GitHub Action being nicely integrated into GitHub and support all the major platforms, it makes sense to migrate the AppVeyor script to GitHub Actions.

- [x] Get a basic build running for Windows
- [x] Auto publish to GitHub on release

Can be done later / separately, after #12 / #11 are merged:
- [ ] Merge changes from #12 / #11 
- [ ] Don't use vcpkg as the extra building of all of SFML dependencies is rather slow
- [ ] Implement Linux builds
- [ ] Implement macOS builds (if not too much effort)

**Comment by SimonHeimberg** [comment]
See my suggestion of a github action in https://github.com/SimonHeimberg/tmp-test-schiffbruch/blob/master/.github/workflows/cmake.yml (I made a copy of the repo to be able to control actions. :hand_over_mouth: )
Linux build works with pr #11: https://github.com/SimonHeimberg/tmp-test-schiffbruch/actions/runs/2603383143
Windows build is prepared but disabled, since I do not know how to get the SFML dependencies.

**Comment by SimonHeimberg** [comment]
The pr above is the action linked in the comment above. It only works on linux (since I do not know how to get the SFML dependencies).

**Comment by eXpl0it3r** [comment]
Implemented with #15 and #17

Thanks for the release tidbits that made it into #17 🙂
